### ISSUE TITLE
Create script to calculate uptime for a range of blocks

### ISSUE THREAD

**Issue by aaronc** [regen-network/testnets#17]
# Context

In the regen-test-1001 testnet we offered the following points: https://github.com/regen-network/testnets/tree/master/regen-test-1001

This issue refers specifically to the uptime reward.

# Acceptance Criteria

Given a blockchain full-node
When the uptime calculation script is run with a start and end block
Then a table of validator keys and the number of blocks where they voted is printed

*Note:* we are interested in validators that voted, not whether or not they were jailed or did not have enough stake. Ideally, we should count any detectable uptime, not just validators that happened to be bonded/unjailed.

**Comment by ethanfrey** [comment]
I think 4, 5, and 6 could be be done with a similar script once the data is there.

6 is total blocks voted / total block in chain

4 and 5 are total blocks voted *in a window of 200 blocks* after two distinct events.

* (4) El Choco upgrade happened at 953628, so we measure votes in 953628-953827: https://medium.com/regen-network/the-upgrade-experience-924a4c903b4f
* (5) Amazonas upgrade happened at 1722051, so we measure the votes in 1722051-1722250

Acceptance criteria should both be the script, and the results of running the queries on the dump from regen-testnet-1001

**Comment by aaronc** [comment]
Exactly

**Comment by ethanfrey** [comment]
This may help:

It syncs all votes from a tendermint node (using rpc interface) and stores the data in postgres for easy queries. https://github.com/iov-one/block-metrics

It handles changing validator sets and records which blocks which validator was active (if we want to punish differently for people who were in the validator set and not signing, and those who hadn't started yet). I think we may have to play around with the calculations for the original values

**Comment by aaronc** [comment]
It's likely big dipper has all this information stored already. @swidnikk has been in touch with Forbole.

**Comment by ethanfrey** [comment]
As a stretch goal, you can also add calculation metrics for (1) and (2). (3) is out of scope - needs the rpc server not big dipper.

(1) - list of all validators on block 1
(2) - list of all addresses who were ever validators on the network

**Comment by anilcse** [comment]
> I think 4, 5, and 6 could be be done with a similar script once the data is there.
> 
> 6 is total blocks voted / total block in chain
> 
> 4 and 5 are total blocks voted _in a window of 200 blocks_ after two distinct events.
> 
> * (4) El Choco upgrade happened at 953628, so we measure votes in 953628-953827: https://medium.com/regen-network/the-upgrade-experience-924a4c903b4f
> * (5) Amazonas upgrade happened at 1722051, so we measure the votes in 1722051-1722250
> 
> Acceptance criteria should both be the script, and the results of running the queries on the dump from regen-testnet-1001

Yes, 4,5 and 6 should be done in same script. Making multiple PRs here would be an over kill I think. May be we should just update the context of the issue, as it is saying "This issue refers specifically to the uptime reward." and PR with 4,5 and 6 fixed. What do you think @aaronc?

**Comment by anilcse** [comment]
> I think 4, 5, and 6 could be be done with a similar script once the data is there.
> 
> 6 is total blocks voted / total block in chain
> 
> 4 and 5 are total blocks voted _in a window of 200 blocks_ after two distinct events.
> 
> * (4) El Choco upgrade happened at 953628, so we measure votes in 953628-953827: https://medium.com/regen-network/the-upgrade-experience-924a4c903b4f
> * (5) Amazonas upgrade happened at 1722051, so we measure the votes in 1722051-1722250
> 
> Acceptance criteria should both be the script, and the results of running the queries on the dump from regen-testnet-1001

@ethanfrey I think for 4 & 5, we should measure votes from next block, right? If upgrade happens at 953628, the validators who upgraded will vote for 953629 block, not for 953628 height. So, we need to measure votes in 953629-953828. Please confirm, the script follows this logic for now.

And also, @ethanfrey  @aaronc , I think we should consider the first block voted in 953629-953828, to distribute upgrade rewards (200 - (953828 - signedBlockHeight)), instead of measuring the votes in 953629-953828. This will allow us to give weight to upgrade event, otherwise it will be same as uptime.

**Comment by ethanfrey** [comment]
I did the +1 already above. But yeah, good eye.

953627 was the last block before the upgrade (the one where the state machine stopped in BeginBlock). As was 1722050.

**Comment by sahith-narahari** [comment]
But we're checking precommits of block which will be present in the next block.
Precommits of block 1 will be present in block 2,so if we're checking if validator signed 100th block we should be checking 101 block's precommits.
