### ISSUE TITLE
cannot add float to u128 yet 

### ISSUE THREAD

**Issue by dirmansebastian** [regen-network/testnets#195]
added 0.5 to amount getting error: no implementation for u128 + float

![image](https://user-images.githubusercontent.com/15945292/76747343-a979df00-6781-11ea-868d-db39e55d13b4.png)

**Comment by anilcse** [comment]
It doesn't support float values. You should use integers and configure decimals for converting back and forth to float when displaying. So, if you configure decimals as `6`, and your tokens balance is, `1,000,680,000` it means you have `1,000.68` tokens.
