### ISSUE TITLE
tendermint-validator-set query error

### ISSUE THREAD

**Issue by novy4** [regen-network/testnets#258]
xrncli q tendermint-validator-set --chain-id=kontraua

ERROR: header has vhash 19A61A4724EE0C117127B655BCCF08A56DA36A7FD73242743A10727FF5B10C76 but valset hash is 9F8456E05C7DA6591F62343CB14AC6493AE34847DC319612DD46DFBFBF73DC20

xrncli version --long
name: wasm
server_name: xrnd
client_name: xrncli
version: 0.7.1
commit: c91f81c25042bfa3ee5890761f818b59914e344b
build_tags: netgo,ledger
go: go version go1.13.8 linux/amd64

**Comment by anilcse** [comment]
Can you try adding `trust-node` flag? It is made mandate for all the queries.

`xrncli q tendermint-validator-set --chain-id=kontraua --trust-node`

**Comment by novy4** [comment]
works fine, thanks
