### ISSUE TITLE
Suggestion about GO path check devnet-val-setup.sh

### ISSUE THREAD

**Issue by matsuro-hadouken** [regen-network/testnets#374]
Been playing with dev-net for a while. It will be nice to add `/usr/local/go` path check for existing installation and if version meet requirements then skip Go install function. Even probably better approach is like `--go-path=/path/to/go` flag pass in to `devnet-val-setup.sh` for people who use different versions for whatever reason. Also avoiding `mv: cannot move 'go' to '/usr/local/go': Directory not empty` error and `./devnet-val-setup.sh: line 27: go: command not found`

Thank you !

**Comment by ryanchristo** [comment]
This is a bit outdated now and no longer an active script. I like the idea but also think in general testing with consistent versions might be more important and manually updating the script is always an option.
