### ISSUE TITLE
Request to Change Mechanism for Community Rewards

### ISSUE THREAD

**Issue by aditya-manit** [regen-network/testnets#690]
Right now in plan.md we can see:

```
Community reward
Top - 10 teams/individuals will receive 50points each for their contributions for the community. technical docs, helping/resolving community issues, etc.
```

> There are a few drawbacks:
> 1) One who answers 10 questions on discord daily gets the same reward as one who answers 1 as long as they both are in Top 10.
> 2) Vague measure of help: I dont undertsand how do we measure the extend of help.
> 3) A very few points are allocation for this section, only 50 :(
> 4) Missing Incentivizes (Like lets say someone creates something which is not mentioned in the doc like discord stickers or memes or raised PRs to improve code or docs)

> My Proposal:
> 1) Create a range of rewards that can be grabbed by someone. [0 - X points]
> 2) In each task we can have a field `"whoHelpedYou"` where users can mention the discord handle of the person who helped them.
> 3) We should allocate some more points to it, like I said have a range. I would suggest [0 to 1000 points] to really incentivize the community to help each other.
> 4) In each submission a user can mention `"whatIdid"` --> where he/she can mention the stuff he worked on. It can solely be decided by team whether it was important or not, or should the team allocate rewards for his/her work or not.

This way we can turn extend of help into a metrics which would help the team to evaluate each person better.
This will have community voice [as they get to say who helped them] and as well as team voice [as they can decide whether the extra effort put by an individual was worth a reward or not].

Hoping my suggestion would be considered :)

**Comment by aditya-manit** [comment]
@anilCSE Let me know of your thoughts on this

**Comment by anilcse** [comment]
Thanks @aditya-manit . The rewards are subjected to change based on the efforts. If we get extra things than what mentioned in the instructions, will reward that too. The suggestion looks good but we would like to keep the focus on testing the software and its bit confusing to introduce new tasks for community rankings. Keep up the good work and everything will follow

**Comment by glandua** [comment]
I agree it may be a bit complex to introduce a subjective ranking system to this. We are tracking contribution (and although it is a centralized, subjective and archaic solution) The Lead validator team will distribute bonus points to particularly active and helpful participants.  I do like the idea of more transparency around bulking up this element (mutualism and co-learning) on the incentive scheme.  The challenge is assigning points in a fair, transparent way.  One nice thing for us about tests in which we can simply measure your success for on chain activities is that it's something we can measure easily using the software we are testing. We can have a think about how to easily measure contribution to the knowledge commons...
