### ISSUE TITLE
Transaction send trough not yet synced node make future transactions impossible to pass.

### ISSUE THREAD

**Issue by matsuro-hadouken** [regen-network/testnets#744]
Way to reproduce:

Start new peer, don't wait until sync, send some transactions trough, wait for peer to fully sync with network. 

After sending transaction trough fully synced peer:

`account sequence mismatch, expected 285, got 284: incorrect account sequence`

How to fix:

Restart node.

Suggestion:

At full sync clear transactions pool.

**Comment by ryanchristo** [comment]
If this is still an issue, the cosmos sdk repository would be the place place to report.
