### ISSUE TITLE
node or validator hangs when uploading contract with gas auto

### ISSUE THREAD

**Issue by levackt** [regen-network/testnets#864]
Can reproduce this by building the contracts in phase-3, and storing using gas=auto
This causes the validator to miss blocks

**Comment by ryanchristo** [comment]
CosmWasm is no longer included in the latest version of regen ledger (v5.0). We may consider adding cosmwasm when there is a version that is compatible with the latest cosmos sdk version but we encourage cosmwasm contract developers to leverage interchain accounts to interact with regen ledger features via IBC.
