### ISSUE TITLE
should devnet-val-setup.sh use a newer version of cosmos-sdk instead of v0.40.0 for cosmovisor?

### ISSUE THREAD

**Issue by patogit** [regen-network/testnets#985]
Is this correct?
https://github.com/regen-network/testnets/blob/master/scripts/devnet-val-setup.sh#L73
Or should it be a newer version?
https://github.com/cosmos/cosmos-sdk/releases
@anilCSE

**Comment by anilcse** [comment]
Yes it should be using new version

**Comment by ryanchristo** [comment]
Resolved in #995
